// This file is generated by Supabase CLI.
// Run: supabase gen types typescript --local > src/types/supabase.ts
// Do not edit manually.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type UserRole = 'public' | 'parent' | 'official'

export interface Database {
  PostgrestVersion: "12"
  public: {
    Tables: {
      club_officials: {
        Row: {
          id: string
          full_name: string
          email: string
          mobile: string
          role: 'admin' | 'coach'
          teams: string[]
          is_primary_contact: boolean
          created_at: string
        }
        Insert: {
          id?: string
          full_name: string
          email: string
          mobile: string
          role: 'admin' | 'coach'
          teams?: string[]
          is_primary_contact?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          email?: string
          mobile?: string
          role?: 'admin' | 'coach'
          teams?: string[]
          is_primary_contact?: boolean
          created_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          id: string
          role: UserRole
          full_name: string | null
          created_at: string
        }
        Insert: {
          id: string
          role?: UserRole
          full_name?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          role?: UserRole
          full_name?: string | null
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      user_role: UserRole
    }
  }
}
