// This file is generated by Supabase CLI.
// Run: supabase gen types typescript --local > src/types/supabase.ts
// Do not edit manually.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type UserRole = 'admin' | 'coach'

export interface Database {
  PostgrestVersion: "12"
  public: {
    Tables: {
      club_officials: {
        Row: {
          id: string
          full_name: string
          email: string
          mobile: string
          role: 'admin' | 'coach'
          teams: string[]
          is_primary_contact: boolean
          created_at: string
        }
        Insert: {
          id?: string
          full_name: string
          email: string
          mobile: string
          role: 'admin' | 'coach'
          teams?: string[]
          is_primary_contact?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          email?: string
          mobile?: string
          role?: 'admin' | 'coach'
          teams?: string[]
          is_primary_contact?: boolean
          created_at?: string
        }
        Relationships: []
      }
      teams: {
        Row: {
          id: string
          name: string
          age_group: string
          primary_contact_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          age_group: string
          primary_contact_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          age_group?: string
          primary_contact_id?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "teams_primary_contact_id_fkey"
            columns: ["primary_contact_id"]
            referencedRelation: "club_officials"
            referencedColumns: ["id"]
          }
        ]
      }
      news_posts: {
        Row: {
          id: string
          title: string
          excerpt: string
          body: string
          cover_image_url: string | null
          images: string[]
          status: 'draft' | 'published' | 'scheduled'
          scheduled_at: string | null
          author_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          excerpt?: string
          body?: string
          cover_image_url?: string | null
          images?: string[]
          status?: 'draft' | 'published' | 'scheduled'
          scheduled_at?: string | null
          author_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          excerpt?: string
          body?: string
          cover_image_url?: string | null
          images?: string[]
          status?: 'draft' | 'published' | 'scheduled'
          scheduled_at?: string | null
          author_id?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "news_posts_author_id_fkey"
            columns: ["author_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      documents: {
        Row: {
          id: string
          name: string
          file_url: string
          file_path: string
          category: string
          audience: 'admin' | 'parents' | 'general'
          uploaded_by: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          file_url: string
          file_path: string
          category?: string
          audience: 'admin' | 'parents' | 'general'
          uploaded_by: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          file_url?: string
          file_path?: string
          category?: string
          audience?: 'admin' | 'parents' | 'general'
          uploaded_by?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "documents_uploaded_by_fkey"
            columns: ["uploaded_by"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      profiles: {
        Row: {
          id: string
          role: UserRole
          full_name: string | null
          created_at: string
        }
        Insert: {
          id: string
          role?: UserRole
          full_name?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          role?: UserRole
          full_name?: string | null
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      user_role: UserRole
      news_post_status: 'draft' | 'published' | 'scheduled'
    }
  }
}
